# Generated by Django 5.0.6 on 2025-01-25 18:39

import customfit.stitches.models
import django.contrib.sites.managers
import django.core.validators
import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("dbtemplates", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ButtonBandTemplate",
            fields=[
                (
                    "template_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="dbtemplates.template",
                    ),
                ),
            ],
            bases=("dbtemplates.template",),
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("on_site", django.contrib.sites.managers.CurrentSiteManager("sites")),
            ],
        ),
        migrations.CreateModel(
            name="ButtonBandVeeneckTemplate",
            fields=[
                (
                    "template_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="dbtemplates.template",
                    ),
                ),
            ],
            bases=("dbtemplates.template",),
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("on_site", django.contrib.sites.managers.CurrentSiteManager("sites")),
            ],
        ),
        migrations.CreateModel(
            name="CowlCastoffEdgeTemplate",
            fields=[
                (
                    "template_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="dbtemplates.template",
                    ),
                ),
            ],
            bases=("dbtemplates.template",),
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("on_site", django.contrib.sites.managers.CurrentSiteManager("sites")),
            ],
        ),
        migrations.CreateModel(
            name="CowlCastonEdgeTemplate",
            fields=[
                (
                    "template_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="dbtemplates.template",
                    ),
                ),
            ],
            bases=("dbtemplates.template",),
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("on_site", django.contrib.sites.managers.CurrentSiteManager("sites")),
            ],
        ),
        migrations.CreateModel(
            name="CowlMainSectionTemplate",
            fields=[
                (
                    "template_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="dbtemplates.template",
                    ),
                ),
            ],
            bases=("dbtemplates.template",),
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("on_site", django.contrib.sites.managers.CurrentSiteManager("sites")),
            ],
        ),
        migrations.CreateModel(
            name="SleeveHemTemplate",
            fields=[
                (
                    "template_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="dbtemplates.template",
                    ),
                ),
            ],
            bases=("dbtemplates.template",),
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("on_site", django.contrib.sites.managers.CurrentSiteManager("sites")),
            ],
        ),
        migrations.CreateModel(
            name="TrimArmholeTemplate",
            fields=[
                (
                    "template_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="dbtemplates.template",
                    ),
                ),
            ],
            bases=("dbtemplates.template",),
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("on_site", django.contrib.sites.managers.CurrentSiteManager("sites")),
            ],
        ),
        migrations.CreateModel(
            name="TrimNecklineTemplate",
            fields=[
                (
                    "template_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="dbtemplates.template",
                    ),
                ),
            ],
            bases=("dbtemplates.template",),
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("on_site", django.contrib.sites.managers.CurrentSiteManager("sites")),
            ],
        ),
        migrations.CreateModel(
            name="WaistHemTemplate",
            fields=[
                (
                    "template_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="dbtemplates.template",
                    ),
                ),
            ],
            bases=("dbtemplates.template",),
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("on_site", django.contrib.sites.managers.CurrentSiteManager("sites")),
            ],
        ),
        migrations.CreateModel(
            name="Stitch",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Examples: 'Garter Stitch', 'Sugar Cube stitch'",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "_patterntext",
                    models.CharField(
                        blank=True,
                        help_text="Text to use for this stitch in patterntext. If left blank, name is used instead. Example: Other Stitch uses 'stitch pattern of your choice.'",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "user_visible",
                    models.BooleanField(
                        default=False,
                        help_text="If set, user will be able to see stitch in Design Wizard.",
                    ),
                ),
                (
                    "repeats_x_mod",
                    models.IntegerField(
                        default=0,
                        help_text=" How many extra stitches are required by the repeat pattern. (If no repeats, put 0.)",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "repeats_mod_y",
                    models.IntegerField(
                        default=1,
                        help_text="How many stitches are in a full repeat. (If no repeats, put 1).",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "stitch_type",
                    models.CharField(
                        choices=[
                            ("lace_stitch", "Lace stitch"),
                            ("cable_stitch", "Cable stitch"),
                            ("textured_stitch", "Textured stitch"),
                            ("ribbing_stitch", "Ribbing stitch"),
                            ("other_stitch_type", "Other stitch type"),
                            ("unknown_stitch_type", "Unknown stitch type"),
                        ],
                        default="unknown_stitch_type",
                        max_length=20,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Notes and written instructions. Enter in Markdown format.",
                        null=True,
                    ),
                ),
                (
                    "short_description",
                    models.TextField(
                        blank=True,
                        help_text="A short description, suitable for characterizing the stitch on, e.g., the stitch list page. Should not be more than a sentence or two. Enter in plain text format.",
                        null=True,
                    ),
                ),
                (
                    "chart",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=customfit.stitches.models._get_image_path,
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=customfit.stitches.models._get_image_path,
                    ),
                ),
                (
                    "extra_notions_text",
                    models.TextField(
                        blank=True,
                        help_text="Extra notions needed for this stitch. Added to the 'Notions' section of a pattern. Can be HTML, but plaintext safer when possible. Ignored if left blank.",
                        null=True,
                    ),
                ),
                ("is_waist_hem_stitch", models.BooleanField(default=False)),
                ("is_sleeve_hem_stitch", models.BooleanField(default=False)),
                ("is_neckline_hem_stitch", models.BooleanField(default=False)),
                ("is_armhole_hem_stitch", models.BooleanField(default=False)),
                ("is_buttonband_hem_stitch", models.BooleanField(default=False)),
                ("is_allover_stitch", models.BooleanField(default=False)),
                ("is_panel_stitch", models.BooleanField(default=False)),
                ("is_accessory_edge_stitch", models.BooleanField(default=False)),
                ("is_accessory_main_stitch", models.BooleanField(default=False)),
                (
                    "extra_finishing_instructions",
                    models.TextField(
                        blank=True,
                        help_text="Text to go into finishing instructions. NOT MARKDOWN: enter in HTML.",
                        null=True,
                    ),
                ),
                (
                    "_button_band_template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="stitches.buttonbandtemplate",
                    ),
                ),
                (
                    "_button_band_veeneck_template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="stitches.buttonbandveenecktemplate",
                    ),
                ),
                (
                    "_cowl_castoff_edge_template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="stitches.cowlcastoffedgetemplate",
                    ),
                ),
                (
                    "_cowl_caston_edge_template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="stitches.cowlcastonedgetemplate",
                    ),
                ),
                (
                    "_cowl_main_section_template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="stitches.cowlmainsectiontemplate",
                    ),
                ),
                (
                    "_sleeve_hem_template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="stitches.sleevehemtemplate",
                    ),
                ),
                (
                    "_trim_armhole_template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="stitches.trimarmholetemplate",
                    ),
                ),
                (
                    "_trim_neckline_template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="stitches.trimnecklinetemplate",
                    ),
                ),
                (
                    "_waist_hem_stitch_template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="stitches.waisthemtemplate",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "stitches",
                "ordering": ["name"],
            },
        ),
    ]
