# Generated by Django 5.0.6 on 2025-01-25 18:39

import customfit.designs.models
import django.contrib.sites.managers
import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("dbtemplates", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdditionalDesignElementTemplate",
            fields=[
                (
                    "template_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="dbtemplates.template",
                    ),
                ),
            ],
            bases=("dbtemplates.template",),
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("on_site", django.contrib.sites.managers.CurrentSiteManager("sites")),
            ],
        ),
        migrations.CreateModel(
            name="Collection",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("creation_date", models.DateField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-creation_date"],
                "get_latest_by": "creation_date",
            },
        ),
        migrations.CreateModel(
            name="Designer",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(
                        help_text="Examples: Taylor Swift, Bjork Gudmundsdottir, Maria-Jose Carreno Quinones. (ASCII characters only)",
                        max_length=200,
                        unique=True,
                    ),
                ),
                (
                    "short_name",
                    models.CharField(
                        help_text="Examples: Taylor, Mrs. Swift, Bjork, Maria-Jose. (ASCII characters only)",
                        max_length=50,
                    ),
                ),
                (
                    "primary_sort_name",
                    models.CharField(
                        help_text="Examples: Swift, Bjork, Carreno Quinones or Quinones (depending on her origin and preference). (ASCII characters only). For internal use only; not for display.",
                        max_length=150,
                    ),
                ),
                (
                    "secondary_sort_name",
                    models.CharField(
                        blank=True,
                        help_text="Examples: Taylor, Gundmundsdottir, Maria-Jose. (ASCII characters only). For internal use only; not for display.",
                        max_length=150,
                        null=True,
                    ),
                ),
                (
                    "primary_home_page",
                    models.URLField(
                        blank=True,
                        help_text="Home page used when we want to make the designer's name into a link.",
                        null=True,
                    ),
                ),
                (
                    "secondary_home_page",
                    models.URLField(
                        blank=True,
                        help_text="Listed after primary home page when explicitly listed in text",
                        null=True,
                    ),
                ),
                (
                    "business_name",
                    models.CharField(
                        blank=True,
                        help_text="Name of associated business. Example: Taylor Nation, The Sugarcubes. (ASCII characters only.)",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "ravelry_link",
                    models.URLField(
                        blank=True,
                        help_text="A full URL to the designer's page in Ravelry.",
                        null=True,
                        validators=[customfit.designs.models.RavelryUrlValidator()],
                    ),
                ),
                (
                    "about_designer_long",
                    models.TextField(
                        blank=True,
                        help_text="1-2 paragraph version of 'About Designer'. Enter in markdown",
                        max_length=2000,
                        null=True,
                        verbose_name="long 'about designer'",
                    ),
                ),
                (
                    "about_designer_short",
                    models.TextField(
                        blank=True,
                        help_text="1-2 sentence version of 'About Designer'. Enter in markdown",
                        max_length=500,
                        null=True,
                        verbose_name="short 'about designer'",
                    ),
                ),
                (
                    "picture",
                    models.ImageField(
                        blank=True,
                        help_text="Head shot preferable",
                        null=True,
                        upload_to=customfit.designs.models.get_designer_image_path,
                    ),
                ),
                ("date_added", models.DateTimeField(auto_now_add=True)),
                ("last_modified", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["primary_sort_name", "secondary_sort_name"],
                "get_latest_by": "date_added",
            },
        ),
        migrations.CreateModel(
            name="ExtraFinishingTemplate",
            fields=[
                (
                    "template_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="dbtemplates.template",
                    ),
                ),
            ],
            bases=("dbtemplates.template",),
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("on_site", django.contrib.sites.managers.CurrentSiteManager("sites")),
            ],
        ),
        migrations.CreateModel(
            name="Design",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "pattern_credits",
                    models.CharField(
                        blank=True,
                        help_text="For any non-authorship and non-photography credits. Example: 'Technical editing: Jane Doe.'",
                        max_length=100,
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="A URL-friendly form of the design's name. Since this is used in URLs, it should not be changed from its initial value. Valid characters include: numbers, letters, hypens, and underscores. (We recommend that you replace spaces with hyphens, for consistent stlying.) Do not use an all-number value, however, as this would conflict with our special handling of old-style design URLs.",
                        unique=True,
                        validators=[
                            customfit.designs.models.NegativeRegexValidator(
                                message="slug cannot be just digits", regex="^[0-9]+$"
                            )
                        ],
                    ),
                ),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("FEATURE", "Featured"),
                            ("PUBLIC", "Viewable by all CF users"),
                            ("LIMITED", "Viewable by subscribers only"),
                            ("PRIVATE", "Not user visible"),
                        ],
                        default="PRIVATE",
                        max_length=7,
                    ),
                ),
                (
                    "purchase_url",
                    models.CharField(
                        help_text="Relative URL where credits for this design can be purchased. If the URL is 'http://example.com/design_foo', for example, put 'design_foo' here. The base URL is taken from the AHD_WC_PRODUCTS_BASE_URL setting/env. NOTE: If you enter a path here with a leading slash ('/design_foo') it will override any path in AHD_WC_PRODUCTS_BASE_URL. Don't do this unless you really want to hard-code the entire path here for some reason.",
                        max_length=100,
                    ),
                ),
                (
                    "ahd_wp_product_id",
                    models.IntegerField(
                        help_text="The product ID (not variation ID) of this design in WooCommerce"
                    ),
                ),
                (
                    "ahd_wp_variation_id",
                    models.IntegerField(
                        blank=True,
                        help_text="The variation ID (not product ID) of this design in WooCommerce",
                        null=True,
                    ),
                ),
                (
                    "difficulty",
                    models.IntegerField(
                        choices=[
                            (1, "Very Easy"),
                            (2, "Easy"),
                            (3, "Intermediate"),
                            (4, "Difficult"),
                            (5, "Expert"),
                        ],
                        help_text="Difficulty rating for this design",
                    ),
                ),
                (
                    "is_basic",
                    models.BooleanField(
                        default=False, help_text="Is this a 'basic' sweater?"
                    ),
                ),
                (
                    "image",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=customfit.designs.models.get_image_path,
                    ),
                ),
                (
                    "cover_sheet",
                    models.FileField(
                        blank=True,
                        help_text="A one- or two-page PDF file to be the first pages of all PDFs for patterns made from this design. Make it pretty! Also, make sure that it's letter-page sized, because it will be added to PDF versions of patterns even it it's not.",
                        null=True,
                        upload_to=customfit.designs.models.get_image_path,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Short description of the design to be displayed to users when they click on it.",
                    ),
                ),
                (
                    "recommended_gauge",
                    models.CharField(
                        blank=True,
                        help_text="Text to go under the 'Recommended Gauge' heading. Will be skipped if absent.",
                        max_length=200,
                    ),
                ),
                (
                    "notions",
                    models.CharField(
                        blank=True,
                        help_text="Text to add under the 'Notions' heading. Will be 'Stitch markers, stitch holder, darning needle' if blank.",
                        max_length=200,
                    ),
                ),
                (
                    "recommended_materials",
                    models.TextField(
                        blank=True,
                        help_text="Text to go under the 'Recommended Materials' heading. Will be skipped if absent. Enter in markdown. Largestheader size should be h3.",
                    ),
                ),
                (
                    "needles",
                    models.CharField(
                        blank=True,
                        help_text="Text to go under the 'Needles' heading. Will be skipped if absent.",
                        max_length=200,
                    ),
                ),
                (
                    "yarn_notes",
                    models.TextField(
                        blank=True,
                        help_text="1 to 2 paragraphs recommended. Follows description in pattern.",
                    ),
                ),
                (
                    "style_notes",
                    models.TextField(
                        blank=True,
                        help_text="Example: 'style adjustment for different bodies'",
                    ),
                ),
                (
                    "collection",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="designs",
                        to="designs.collection",
                    ),
                ),
                (
                    "polymorphic_ctype",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="polymorphic_%(app_label)s.%(class)s_set+",
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "designer",
                    models.ForeignKey(
                        help_text="Required",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="designs",
                        to="designs.designer",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="DesignAlternatePicture",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to=customfit.designs.models.get_image_path
                    ),
                ),
                (
                    "design",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alternate_images",
                        to="designs.design",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
