# Generated by Django 5.0.6 on 2025-01-25 18:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("pattern_spec", "0001_initial"),
        ("swatches", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="patternspec",
            name="swatch",
            field=models.ForeignKey(
                help_text="Swatch for which this design is intended",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="swatches.swatch",
            ),
        ),
        migrations.AddField(
            model_name="patternspec",
            name="user",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
