# Generated by Django 5.0.6 on 2025-01-25 18:39

import customfit.fields
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cowls", "0001_initial"),
        ("designs", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CowlDesign",
            fields=[
                (
                    "design_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="designs.design",
                    ),
                ),
                (
                    "circumference",
                    models.CharField(
                        choices=[
                            ("cowl_circ_xsmall", "extra-small circumference"),
                            ("cowl_circ_small", "small circumference"),
                            ("cowl_circ_medium", "medium circumference"),
                            ("cowl_circ_large", "large circumference"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "height",
                    models.CharField(
                        choices=[
                            ("cowl_height_short", "short height"),
                            ("cowl_height_avg", "average height"),
                            ("cowl_height_tall", "tall height"),
                            ("cowl_height_xtall", "extra tall height"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "edging_stitch_height",
                    customfit.fields.LengthField(
                        help_text="How high you'd like the edging stitch pattern to be, in inches. Note: will be applied twice-- once at cast on and once at cast off.",
                        validators=[
                            django.core.validators.MinValueValidator(
                                0.25,
                                message="Ensure this value is greater than or equal to Â&quot;/0.5cm",
                            ),
                            django.core.validators.MaxValueValidator(
                                4,
                                message="Ensure this value is less than or equal to 4&quot;/10.5cm",
                            ),
                            django.core.validators.MinValueValidator(0),
                        ],
                    ),
                ),
                (
                    "cast_on_x_mod",
                    models.IntegerField(
                        default=0,
                        help_text=" How many extra stitches are required at cast on. (If no repeats, put 0.)",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "cast_on_mod_y",
                    models.IntegerField(
                        default=1,
                        help_text="How many stitches are in a full repeat at cast on. (If no repeats, put 1.)",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "extra_cable_stitches",
                    models.IntegerField(
                        default=0,
                        help_text="How many extra stitches to add for a cable. (If none, put 0.)",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "extra_cable_stitches_are_main_pattern_only",
                    models.BooleanField(
                        default=False,
                        help_text="If true, then extra_cable_stitches are added to main pattern counts but not cast-on or bind-off",
                    ),
                ),
                (
                    "horizontal_panel_rounds",
                    customfit.fields.NonNegSmallIntegerField(
                        default=0,
                        help_text="How many stitches to devote to each horizontal panel",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("designs.design", models.Model),
        ),
    ]
