# Generated by Django 5.0.6 on 2025-01-25 18:39

import customfit.cowls.models
import customfit.fields
import django.contrib.sites.managers
import django.core.validators
import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cowls", "0002_initial"),
        ("dbtemplates", "0001_initial"),
        ("garment_parameters", "0003_initial"),
        ("pattern_spec", "0001_initial"),
        ("patterns", "0001_initial"),
        ("pieces", "0001_initial"),
        ("schematics", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CowlGarmentSchematic",
            fields=[
                (
                    "constructionschematic_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="schematics.constructionschematic",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("schematics.constructionschematic",),
        ),
        migrations.CreateModel(
            name="CowlGradedGarmentParametersGrade",
            fields=[
                (
                    "gradedgarmentparametersgrade_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="garment_parameters.gradedgarmentparametersgrade",
                    ),
                ),
                (
                    "height",
                    customfit.fields.LengthField(
                        help_text="Height of the cowl in inches",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "circumference",
                    customfit.cowls.models.CowlCircumferenceField(
                        help_text="Circumference of the cowl in inches",
                        validators=[django.core.validators.MinValueValidator(18)],
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("garment_parameters.gradedgarmentparametersgrade", models.Model),
        ),
        migrations.CreateModel(
            name="CowlIndividualGarmentParameters",
            fields=[
                (
                    "individualgarmentparameters_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="garment_parameters.individualgarmentparameters",
                    ),
                ),
                (
                    "height",
                    customfit.fields.LengthField(
                        help_text="Height of the cowl in inches",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "circumference",
                    customfit.cowls.models.CowlCircumferenceField(
                        help_text="Circumference of the cowl in inches",
                        validators=[django.core.validators.MinValueValidator(18)],
                    ),
                ),
                (
                    "edging_height",
                    customfit.fields.LengthField(
                        help_text="Height of the edging (on both top and bottom)",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("garment_parameters.individualgarmentparameters", models.Model),
        ),
        migrations.CreateModel(
            name="CowlPattern",
            fields=[
                (
                    "individualpattern_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="patterns.individualpattern",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("patterns.individualpattern",),
        ),
        migrations.CreateModel(
            name="CowlPatternPieces",
            fields=[
                (
                    "patternpieces_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="pieces.patternpieces",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(customfit.cowls.models.CowlAreaMixin, "pieces.patternpieces"),
        ),
        migrations.CreateModel(
            name="CowlPatternSpec",
            fields=[
                (
                    "patternspec_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="pattern_spec.patternspec",
                    ),
                ),
                (
                    "circumference",
                    models.CharField(
                        choices=[
                            ("cowl_circ_xsmall", "extra-small circumference"),
                            ("cowl_circ_small", "small circumference"),
                            ("cowl_circ_medium", "medium circumference"),
                            ("cowl_circ_large", "large circumference"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "height",
                    models.CharField(
                        choices=[
                            ("cowl_height_short", "short height"),
                            ("cowl_height_avg", "average height"),
                            ("cowl_height_tall", "tall height"),
                            ("cowl_height_xtall", "extra tall height"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "edging_stitch_height",
                    customfit.fields.LengthField(
                        help_text="How high you'd like the edging stitch pattern to be, in inches. Note: will be applied twice-- once at cast on and once at cast off.",
                        validators=[
                            django.core.validators.MinValueValidator(
                                0.25,
                                message="Ensure this value is greater than or equal to Â&quot;/0.5cm",
                            ),
                            django.core.validators.MaxValueValidator(
                                4,
                                message="Ensure this value is less than or equal to 4&quot;/10.5cm",
                            ),
                            django.core.validators.MinValueValidator(0),
                        ],
                    ),
                ),
                (
                    "cast_on_x_mod",
                    models.IntegerField(
                        default=0,
                        help_text=" How many extra stitches are required at cast on. (If no repeats, put 0.)",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "cast_on_mod_y",
                    models.IntegerField(
                        default=1,
                        help_text="How many stitches are in a full repeat at cast on. (If no repeats, put 1.)",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "extra_cable_stitches",
                    models.IntegerField(
                        default=0,
                        help_text="How many extra stitches to add for a cable. (If none, put 0.)",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "extra_cable_stitches_are_main_pattern_only",
                    models.BooleanField(
                        default=False,
                        help_text="If true, then extra_cable_stitches are added to main pattern counts but not cast-on or bind-off",
                    ),
                ),
                (
                    "horizontal_panel_rounds",
                    customfit.fields.NonNegSmallIntegerField(
                        default=0,
                        help_text="How many stitches to devote to each horizontal panel",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("pattern_spec.patternspec", models.Model),
        ),
        migrations.CreateModel(
            name="CowlPiece",
            fields=[
                (
                    "patternpiece_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="pieces.patternpiece",
                    ),
                ),
                (
                    "cast_on_stitches",
                    customfit.fields.StrictPositiveSmallIntegerField(
                        validators=[customfit.fields.LowerLimitValidator(0)]
                    ),
                ),
                (
                    "main_pattern_stitches",
                    customfit.fields.StrictPositiveSmallIntegerField(
                        validators=[customfit.fields.LowerLimitValidator(0)]
                    ),
                ),
                (
                    "edging_height_in_rows",
                    customfit.fields.StrictPositiveSmallIntegerField(
                        validators=[customfit.fields.LowerLimitValidator(0)]
                    ),
                ),
                (
                    "total_rows",
                    customfit.fields.StrictPositiveSmallIntegerField(
                        validators=[customfit.fields.LowerLimitValidator(0)]
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("pieces.patternpiece", models.Model),
        ),
        migrations.CreateModel(
            name="CowlPieceSchematic",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "height",
                    customfit.fields.LengthField(
                        validators=[django.core.validators.MinValueValidator(0)]
                    ),
                ),
                (
                    "circumference",
                    customfit.fields.LengthField(
                        validators=[django.core.validators.MinValueValidator(0)]
                    ),
                ),
                (
                    "edging_height",
                    customfit.fields.LengthField(
                        validators=[django.core.validators.MinValueValidator(0)]
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CowlRedo",
            fields=[
                (
                    "redo_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="patterns.redo",
                    ),
                ),
                (
                    "circumference",
                    models.CharField(
                        choices=[
                            ("cowl_circ_xsmall", "extra-small circumference"),
                            ("cowl_circ_small", "small circumference"),
                            ("cowl_circ_medium", "medium circumference"),
                            ("cowl_circ_large", "large circumference"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "height",
                    models.CharField(
                        choices=[
                            ("cowl_height_short", "short height"),
                            ("cowl_height_avg", "average height"),
                            ("cowl_height_tall", "tall height"),
                            ("cowl_height_xtall", "extra tall height"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("patterns.redo", models.Model),
        ),
        migrations.CreateModel(
            name="FinalEdgingTemplate",
            fields=[
                (
                    "template_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="dbtemplates.template",
                    ),
                ),
            ],
            bases=("dbtemplates.template",),
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("on_site", django.contrib.sites.managers.CurrentSiteManager("sites")),
            ],
        ),
        migrations.CreateModel(
            name="FirstEdgingTemplate",
            fields=[
                (
                    "template_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="dbtemplates.template",
                    ),
                ),
            ],
            bases=("dbtemplates.template",),
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("on_site", django.contrib.sites.managers.CurrentSiteManager("sites")),
            ],
        ),
        migrations.CreateModel(
            name="GradedCowlGarmentParameters",
            fields=[
                (
                    "gradedgarmentparameters_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="garment_parameters.gradedgarmentparameters",
                    ),
                ),
                (
                    "edging_height",
                    customfit.fields.LengthField(
                        help_text="Height of the edging (on both top and bottom)",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("garment_parameters.gradedgarmentparameters", models.Model),
        ),
        migrations.CreateModel(
            name="GradedCowlGarmentSchematic",
            fields=[
                (
                    "gradedconstructionschematic_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="schematics.gradedconstructionschematic",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("schematics.gradedconstructionschematic",),
        ),
        migrations.CreateModel(
            name="GradedCowlPattern",
            fields=[
                (
                    "gradedpattern_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="patterns.gradedpattern",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("patterns.gradedpattern",),
        ),
        migrations.CreateModel(
            name="GradedCowlPatternPieces",
            fields=[
                (
                    "gradedpatternpieces_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="pieces.gradedpatternpieces",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("pieces.gradedpatternpieces",),
        ),
        migrations.CreateModel(
            name="GradedCowlPatternSpec",
            fields=[
                (
                    "gradedpatternspec_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="pattern_spec.gradedpatternspec",
                    ),
                ),
                (
                    "edging_stitch_height",
                    customfit.fields.LengthField(
                        help_text="How high you'd like the edging stitch pattern to be, in inches. Note: will be applied twice-- once at cast on and once at cast off.",
                        validators=[
                            django.core.validators.MinValueValidator(
                                0.25,
                                message="Ensure this value is greater than or equal to Â&quot;/0.5cm",
                            ),
                            django.core.validators.MaxValueValidator(
                                4,
                                message="Ensure this value is less than or equal to 4&quot;/10.5cm",
                            ),
                            django.core.validators.MinValueValidator(0),
                        ],
                    ),
                ),
                (
                    "cast_on_x_mod",
                    models.IntegerField(
                        default=0,
                        help_text=" How many extra stitches are required at cast on. (If no repeats, put 0.)",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "cast_on_mod_y",
                    models.IntegerField(
                        default=1,
                        help_text="How many stitches are in a full repeat at cast on. (If no repeats, put 1.)",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "extra_cable_stitches",
                    models.IntegerField(
                        default=0,
                        help_text="How many extra stitches to add for a cable. (If none, put 0.)",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "extra_cable_stitches_are_main_pattern_only",
                    models.BooleanField(
                        default=False,
                        help_text="If true, then extra_cable_stitches are added to main pattern counts but not cast-on or bind-off",
                    ),
                ),
                (
                    "horizontal_panel_rounds",
                    customfit.fields.NonNegSmallIntegerField(
                        default=0,
                        help_text="How many stitches to devote to each horizontal panel",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "row_gauge",
                    models.FloatField(help_text="Number of rows over four inches"),
                ),
                (
                    "stitch_gauge",
                    models.FloatField(help_text="Number of stitches over four inches"),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("pattern_spec.gradedpatternspec", models.Model),
        ),
        migrations.CreateModel(
            name="GradedCowlPiece",
            fields=[
                (
                    "gradedpatternpiece_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="pieces.gradedpatternpiece",
                    ),
                ),
                (
                    "cast_on_stitches",
                    customfit.fields.StrictPositiveSmallIntegerField(
                        validators=[customfit.fields.LowerLimitValidator(0)]
                    ),
                ),
                (
                    "main_pattern_stitches",
                    customfit.fields.StrictPositiveSmallIntegerField(
                        validators=[customfit.fields.LowerLimitValidator(0)]
                    ),
                ),
                (
                    "edging_height_in_rows",
                    customfit.fields.StrictPositiveSmallIntegerField(
                        validators=[customfit.fields.LowerLimitValidator(0)]
                    ),
                ),
                (
                    "total_rows",
                    customfit.fields.StrictPositiveSmallIntegerField(
                        validators=[customfit.fields.LowerLimitValidator(0)]
                    ),
                ),
            ],
            options={
                "ordering": ["sort_key"],
            },
            bases=("pieces.gradedpatternpiece", models.Model),
        ),
        migrations.CreateModel(
            name="GradedCowlPieceSchematic",
            fields=[
                (
                    "gradedpieceschematic_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="schematics.gradedpieceschematic",
                    ),
                ),
                (
                    "height",
                    customfit.fields.LengthField(
                        validators=[django.core.validators.MinValueValidator(0)]
                    ),
                ),
                (
                    "circumference",
                    customfit.fields.LengthField(
                        validators=[django.core.validators.MinValueValidator(0)]
                    ),
                ),
                (
                    "edging_height",
                    customfit.fields.LengthField(
                        validators=[django.core.validators.MinValueValidator(0)]
                    ),
                ),
            ],
            bases=("schematics.gradedpieceschematic", models.Model),
        ),
        migrations.CreateModel(
            name="MainSectionTemplate",
            fields=[
                (
                    "template_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="dbtemplates.template",
                    ),
                ),
            ],
            bases=("dbtemplates.template",),
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("on_site", django.contrib.sites.managers.CurrentSiteManager("sites")),
            ],
        ),
        migrations.CreateModel(
            name="StitchTemplateCowlEdge",
            fields=[
                (
                    "template_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="dbtemplates.template",
                    ),
                ),
            ],
            bases=("dbtemplates.template",),
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("on_site", django.contrib.sites.managers.CurrentSiteManager("sites")),
            ],
        ),
        migrations.CreateModel(
            name="StitchTemplateCowlMain",
            fields=[
                (
                    "template_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="dbtemplates.template",
                    ),
                ),
            ],
            bases=("dbtemplates.template",),
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("on_site", django.contrib.sites.managers.CurrentSiteManager("sites")),
            ],
        ),
    ]
