# Generated by Django 5.0.6 on 2025-01-25 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("cowls", "0003_initial"),
        ("stitches", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="additionalstitch",
            name="stitch",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_stitch",
                to="stitches.stitch",
            ),
        ),
        migrations.AddField(
            model_name="cowldesign",
            name="cable_stitch",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"stitch_type": "cable_stitch"},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_cable_stitch_%(class)s",
                to="stitches.stitch",
            ),
        ),
        migrations.AddField(
            model_name="cowldesign",
            name="edging_stitch",
            field=models.ForeignKey(
                limit_choices_to={"is_accessory_edge_stitch": True},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_edging_stitch_%(class)s",
                to="stitches.stitch",
            ),
        ),
        migrations.AddField(
            model_name="cowldesign",
            name="main_stitch",
            field=models.ForeignKey(
                limit_choices_to={"is_accessory_main_stitch": True},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_main_stitch_%(class)s",
                to="stitches.stitch",
            ),
        ),
        migrations.AddField(
            model_name="cowldesign",
            name="panel_stitch",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"is_panel_stitch": True},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_panel_stitch_%(class)s",
                to="stitches.stitch",
            ),
        ),
        migrations.AddField(
            model_name="additionalstitch",
            name="design",
            field=models.ForeignKey(
                help_text="The design that should include this additional stitch",
                on_delete=django.db.models.deletion.CASCADE,
                to="cowls.cowldesign",
            ),
        ),
        migrations.AddField(
            model_name="cowlpatternspec",
            name="cable_stitch",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"stitch_type": "cable_stitch"},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_cable_stitch_%(class)s",
                to="stitches.stitch",
            ),
        ),
        migrations.AddField(
            model_name="cowlpatternspec",
            name="edging_stitch",
            field=models.ForeignKey(
                limit_choices_to={"is_accessory_edge_stitch": True},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_edging_stitch_%(class)s",
                to="stitches.stitch",
            ),
        ),
        migrations.AddField(
            model_name="cowlpatternspec",
            name="main_stitch",
            field=models.ForeignKey(
                limit_choices_to={"is_accessory_main_stitch": True},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_main_stitch_%(class)s",
                to="stitches.stitch",
            ),
        ),
        migrations.AddField(
            model_name="cowlpatternspec",
            name="panel_stitch",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"is_panel_stitch": True},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_panel_stitch_%(class)s",
                to="stitches.stitch",
            ),
        ),
        migrations.AddField(
            model_name="cowlpiece",
            name="schematic",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="cowls.cowlgarmentschematic",
            ),
        ),
        migrations.AddField(
            model_name="cowlpatternpieces",
            name="cowl",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="cowls.cowlpiece"
            ),
        ),
        migrations.AddField(
            model_name="cowlpieceschematic",
            name="polymorphic_ctype",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="polymorphic_%(app_label)s.%(class)s_set+",
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="cowlgarmentschematic",
            name="cowl_piece",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="cowls.cowlpieceschematic",
            ),
        ),
        migrations.AddField(
            model_name="cowldesign",
            name="final_edging_template",
            field=models.ForeignKey(
                blank=True,
                help_text="Replaces default template(s) when present. Note: Template should start with {% load pattern_conventions %} and be 'complete' HTML (include liminal p or h3 tags).",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="cowls.finaledgingtemplate",
            ),
        ),
        migrations.AddField(
            model_name="cowldesign",
            name="first_edging_template",
            field=models.ForeignKey(
                blank=True,
                help_text="Replaces default template(s) when present. Note: Template should start with {% load pattern_conventions %} and be 'complete' HTML (include liminal p or h3 tags).",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="cowls.firstedgingtemplate",
            ),
        ),
        migrations.AddField(
            model_name="gradedcowlpatternspec",
            name="cable_stitch",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"stitch_type": "cable_stitch"},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_cable_stitch_%(class)s",
                to="stitches.stitch",
            ),
        ),
        migrations.AddField(
            model_name="gradedcowlpatternspec",
            name="edging_stitch",
            field=models.ForeignKey(
                limit_choices_to={"is_accessory_edge_stitch": True},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_edging_stitch_%(class)s",
                to="stitches.stitch",
            ),
        ),
        migrations.AddField(
            model_name="gradedcowlpatternspec",
            name="main_stitch",
            field=models.ForeignKey(
                limit_choices_to={"is_accessory_main_stitch": True},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_main_stitch_%(class)s",
                to="stitches.stitch",
            ),
        ),
        migrations.AddField(
            model_name="gradedcowlpatternspec",
            name="panel_stitch",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"is_panel_stitch": True},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_panel_stitch_%(class)s",
                to="stitches.stitch",
            ),
        ),
        migrations.AddField(
            model_name="cowldesign",
            name="main_section_template",
            field=models.ForeignKey(
                blank=True,
                help_text="Replaces default template(s) when present. Note: Template should start with {% load pattern_conventions %} and be 'complete' HTML (include liminal p or h3 tags).",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="cowls.mainsectiontemplate",
            ),
        ),
        migrations.AddField(
            model_name="stitchtemplatecowledge",
            name="stitch",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="stitches.stitch"
            ),
        ),
        migrations.AddField(
            model_name="stitchtemplatecowlmain",
            name="stitch",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="stitches.stitch"
            ),
        ),
    ]
