# Generated by Django 5.0.6 on 2025-01-25 18:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("garment_parameters", "0001_initial"),
        ("pattern_spec", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="gradedgarmentparameters",
            name="pattern_spec",
            field=models.ForeignKey(
                help_text="Spec from which these parameters was derived",
                on_delete=django.db.models.deletion.CASCADE,
                to="pattern_spec.gradedpatternspec",
            ),
        ),
        migrations.AddField(
            model_name="gradedgarmentparameters",
            name="polymorphic_ctype",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="polymorphic_%(app_label)s.%(class)s_set+",
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="gradedgarmentparameters",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="gradedgarmentparametersgrade",
            name="graded_garment_parameters",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="gradedgarmentparametersgrade_set",
                to="garment_parameters.gradedgarmentparameters",
            ),
        ),
        migrations.AddField(
            model_name="gradedgarmentparametersgrade",
            name="polymorphic_ctype",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="polymorphic_%(app_label)s.%(class)s_set+",
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="individualgarmentparameters",
            name="pattern_spec",
            field=models.ForeignKey(
                blank=True,
                help_text="Spec from which these parameters was derived",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="pattern_spec.patternspec",
            ),
        ),
        migrations.AddField(
            model_name="individualgarmentparameters",
            name="polymorphic_ctype",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="polymorphic_%(app_label)s.%(class)s_set+",
                to="contenttypes.contenttype",
            ),
        ),
    ]
