# Generated by Django 5.0.6 on 2025-01-25 18:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("garment_parameters", "0002_initial"),
        ("patterns", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="individualgarmentparameters",
            name="redo",
            field=models.ForeignKey(
                blank=True,
                help_text="Spec from which these parameters was derived",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="patterns.redo",
            ),
        ),
        migrations.AddField(
            model_name="individualgarmentparameters",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
