# Generated by Django 5.0.6 on 2025-01-25 18:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField(default=django.utils.timezone.now)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=6)),
                (
                    "paypal_signal",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("success", "payment_was_successful"),
                            ("flagged", "payment_was_flagged"),
                        ],
                        max_length=7,
                    ),
                ),
                ("approved", models.BooleanField(default=False)),
                ("paypal_transaction_id", models.CharField(blank=True, max_length=17)),
                ("paypal_payer_email", models.EmailField(blank=True, max_length=254)),
                (
                    "why_free",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("first_beta_tester", "first-beta-tester pattern"),
                            ("alpha_yarnstore", "LYS alpha-tester pattern"),
                            ("staff_user", "staff-user pattern"),
                            ("maker_plus", "maker-plus pattern"),
                            ("maker", "maker pattern"),
                            ("credit_used", "credit used"),
                            ("coupon_used", "full-value coupon used"),
                            ("lys_sub_free", "LYS-account free pattern"),
                            ("unknown_reason", "unknown reason"),
                            ("lys_customer_copy", "copied from LYS account"),
                            ("friend_and_family", "friend or family"),
                        ],
                        max_length=30,
                        null=True,
                    ),
                ),
            ],
        ),
    ]
