# Generated by Django 5.0.6 on 2025-01-25 18:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("patterns", "0001_initial"),
        ("pieces", "0002_initial"),
        ("swatches", "0002_initial"),
        ("uploads", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="gradedpattern",
            name="featured_pic",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="uploads.individualpatternpicture",
            ),
        ),
        migrations.AddField(
            model_name="gradedpattern",
            name="pieces",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="pieces.gradedpatternpieces",
            ),
        ),
        migrations.AddField(
            model_name="gradedpattern",
            name="polymorphic_ctype",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="polymorphic_%(app_label)s.%(class)s_set+",
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="individualpattern",
            name="featured_pic",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="uploads.individualpatternpicture",
            ),
        ),
        migrations.AddField(
            model_name="individualpattern",
            name="original_pieces",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="pieces.patternpieces",
            ),
        ),
        migrations.AddField(
            model_name="individualpattern",
            name="pieces",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="pieces.patternpieces"
            ),
        ),
        migrations.AddField(
            model_name="individualpattern",
            name="polymorphic_ctype",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="polymorphic_%(app_label)s.%(class)s_set+",
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="individualpattern",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="redo",
            name="pattern",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="patterns.individualpattern",
            ),
        ),
        migrations.AddField(
            model_name="redo",
            name="polymorphic_ctype",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="polymorphic_%(app_label)s.%(class)s_set+",
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="redo",
            name="swatch",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="swatches.swatch"
            ),
        ),
    ]
