# Generated by Django 5.0.6 on 2025-01-25 18:39

import customfit.fields
import customfit.test_garment.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("bodies", "0002_initial"),
        ("contenttypes", "0002_remove_content_type_name"),
        ("designs", "0001_initial"),
        ("garment_parameters", "0003_initial"),
        ("pattern_spec", "0002_initial"),
        ("patterns", "0002_initial"),
        ("pieces", "0002_initial"),
        ("schematics", "0001_initial"),
        ("stitches", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GradedTestGarmentParameters",
            fields=[
                (
                    "gradedgarmentparameters_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="garment_parameters.gradedgarmentparameters",
                    ),
                ),
                (
                    "test_field",
                    customfit.fields.LengthField(
                        validators=[django.core.validators.MinValueValidator(0)]
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("garment_parameters.gradedgarmentparameters", models.Model),
        ),
        migrations.CreateModel(
            name="GradedTestGarmentParametersGrade",
            fields=[
                (
                    "gradedgarmentparametersgrade_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="garment_parameters.gradedgarmentparametersgrade",
                    ),
                ),
                (
                    "test_field_from_body",
                    customfit.fields.LengthField(
                        validators=[django.core.validators.MinValueValidator(0)]
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("garment_parameters.gradedgarmentparametersgrade", models.Model),
        ),
        migrations.CreateModel(
            name="GradedTestGarmentSchematic",
            fields=[
                (
                    "gradedconstructionschematic_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="schematics.gradedconstructionschematic",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("schematics.gradedconstructionschematic",),
        ),
        migrations.CreateModel(
            name="GradedTestPattern",
            fields=[
                (
                    "gradedpattern_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="patterns.gradedpattern",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("patterns.gradedpattern", models.Model),
        ),
        migrations.CreateModel(
            name="GradedTestPatternPiece",
            fields=[
                (
                    "gradedpatternpiece_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="pieces.gradedpatternpiece",
                    ),
                ),
                ("test_field", models.FloatField()),
            ],
            options={
                "ordering": ["sort_key"],
            },
            bases=("pieces.gradedpatternpiece", models.Model),
        ),
        migrations.CreateModel(
            name="GradedTestPatternPieces",
            fields=[
                (
                    "gradedpatternpieces_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="pieces.gradedpatternpieces",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("pieces.gradedpatternpieces", models.Model),
        ),
        migrations.CreateModel(
            name="GradedTestPieceSchematic",
            fields=[
                (
                    "gradedpieceschematic_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="schematics.gradedpieceschematic",
                    ),
                ),
                ("test_field", models.FloatField()),
                ("test_field_from_body", models.FloatField()),
            ],
            options={
                "abstract": False,
            },
            bases=("schematics.gradedpieceschematic", models.Model),
        ),
        migrations.CreateModel(
            name="TestDesign",
            fields=[
                (
                    "design_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="designs.design",
                    ),
                ),
                (
                    "test_length",
                    customfit.fields.LengthField(
                        validators=[django.core.validators.MinValueValidator(0)]
                    ),
                ),
                (
                    "stitch1",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="stitches.stitch",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("designs.design",),
        ),
        migrations.CreateModel(
            name="TestGarmentParameters",
            fields=[
                (
                    "individualgarmentparameters_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="garment_parameters.individualgarmentparameters",
                    ),
                ),
                (
                    "test_field",
                    customfit.fields.LengthField(
                        validators=[django.core.validators.MinValueValidator(0)]
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("garment_parameters.individualgarmentparameters", models.Model),
        ),
        migrations.CreateModel(
            name="TestIndividualPattern",
            fields=[
                (
                    "individualpattern_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="patterns.individualpattern",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("patterns.individualpattern", models.Model),
        ),
        migrations.CreateModel(
            name="TestPatternPiece",
            fields=[
                (
                    "patternpiece_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="pieces.patternpiece",
                    ),
                ),
                ("test_field", models.FloatField()),
            ],
            options={
                "abstract": False,
            },
            bases=("pieces.patternpiece", models.Model),
        ),
        migrations.CreateModel(
            name="TestPatternSpec",
            fields=[
                (
                    "patternspec_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="pattern_spec.patternspec",
                    ),
                ),
                (
                    "test_length",
                    customfit.fields.LengthField(
                        validators=[django.core.validators.MinValueValidator(0)]
                    ),
                ),
                (
                    "stitch1",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="stitches.stitch",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("pattern_spec.patternspec", models.Model),
        ),
        migrations.CreateModel(
            name="TestRedo",
            fields=[
                (
                    "redo_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="patterns.redo",
                    ),
                ),
                (
                    "test_length",
                    customfit.fields.LengthField(
                        validators=[django.core.validators.MinValueValidator(0)]
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("patterns.redo",),
        ),
        migrations.CreateModel(
            name="GradedTestPatternSpec",
            fields=[
                (
                    "gradedpatternspec_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="pattern_spec.gradedpatternspec",
                    ),
                ),
                (
                    "test_length",
                    customfit.fields.LengthField(
                        validators=[django.core.validators.MinValueValidator(0)]
                    ),
                ),
                ("row_gauge", models.FloatField()),
                ("stitch_gauge", models.FloatField()),
                (
                    "grade_set",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bodies.gradeset",
                    ),
                ),
                (
                    "stitch1",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="stitches.stitch",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("pattern_spec.gradedpatternspec", models.Model),
        ),
        migrations.CreateModel(
            name="TestAdditionalDesignElement",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Note: will be visible to users", max_length=100
                    ),
                ),
                (
                    "height_value",
                    models.FloatField(
                        help_text="If height is row-valued, the row-count should be an integer that includes start *and* end row. Elements with 'no' height should be entered as having height of 1 row. Note: this value is ignored if the element's height is 'no end'.",
                        validators=[customfit.fields.LowerLimitValidator(0)],
                    ),
                ),
                (
                    "height_type",
                    models.CharField(
                        choices=[
                            ("height_in_inches", "inches"),
                            ("height_in_rows", "rows"),
                            ("height_no_end", "no end"),
                        ],
                        default="height_in_inches",
                        help_text="Elements with 'no' height should be entered as having height of 1 row.",
                        max_length=20,
                    ),
                ),
                (
                    "overlap_behavior",
                    models.CharField(
                        choices=[
                            ("overlap_inform", "purely informational"),
                            ("overlap_instruct", "instructions"),
                            ("overlap_start", "start only"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "start_location_value",
                    customfit.fields.NonNegFloatField(
                        help_text="Can be zero, but not negative.",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "start_location_type",
                    models.CharField(
                        choices=[
                            ("start_after_caston", "inches after castons"),
                            ("start_before_cap", "inches before cap-shaping start"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "design",
                    models.ForeignKey(
                        help_text="The design that should include this additional element",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="designs.design",
                    ),
                ),
                (
                    "stitch",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to=models.Q(
                            ("is_panel_stitch", True),
                            ("is_allover_stitch", True),
                            _connector="OR",
                        ),
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_stitch",
                        to="stitches.stitch",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        help_text="Template for this additional-element. Note: Template should start with {% load pattern_conventions %} and be 'complete' HTML (include liminal p or h3 tags). The associated piece will be availableunder the name 'piece'.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="designs.additionaldesignelementtemplate",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TestDesignWithBody",
            fields=[
                (
                    "testdesign_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="test_garment.testdesign",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("test_garment.testdesign",),
        ),
        migrations.CreateModel(
            name="TestGarmentParametersWithBody",
            fields=[
                (
                    "testgarmentparameters_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="test_garment.testgarmentparameters",
                    ),
                ),
                (
                    "test_field_from_body",
                    customfit.fields.LengthField(
                        validators=[django.core.validators.MinValueValidator(0)]
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("test_garment.testgarmentparameters", models.Model),
        ),
        migrations.CreateModel(
            name="TestPatternPieces",
            fields=[
                (
                    "patternpieces_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="pieces.patternpieces",
                    ),
                ),
                (
                    "test_piece",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="test_garment.testpatternpiece",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(
                customfit.test_garment.models.TestGarmentAreaMixin,
                "pieces.patternpieces",
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="TestPieceSchematic",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("test_field", models.FloatField()),
                (
                    "polymorphic_ctype",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="polymorphic_%(app_label)s.%(class)s_set+",
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TestGarmentSchematic",
            fields=[
                (
                    "constructionschematic_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="schematics.constructionschematic",
                    ),
                ),
                (
                    "test_piece",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="test_garment.testpieceschematic",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("schematics.constructionschematic",),
        ),
        migrations.CreateModel(
            name="TestPatternSpecWithBody",
            fields=[
                (
                    "testpatternspec_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="test_garment.testpatternspec",
                    ),
                ),
                (
                    "body",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="bodies.body"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("test_garment.testpatternspec",),
        ),
        migrations.CreateModel(
            name="TestRedoWithBody",
            fields=[
                (
                    "testredo_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="test_garment.testredo",
                    ),
                ),
                (
                    "body",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="bodies.body"
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("test_garment.testredo",),
        ),
    ]
