# Generated by Django 5.0.6 on 2025-01-25 18:39

import customfit.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Body",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "body_type",
                    models.CharField(
                        choices=[
                            ("body_type_adult_woman", "Adult woman"),
                            ("body_type_adult_man", "Adult man"),
                            ("body_type_child", "Child"),
                            ("body_type_unstated", "I'd prefer not to say"),
                        ],
                        default="body_type_unstated",
                        max_length=25,
                    ),
                ),
                (
                    "waist_circ",
                    customfit.fields.LengthField(
                        help_text="Full circumference, in inches",
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="waist circumference",
                    ),
                ),
                (
                    "bust_circ",
                    customfit.fields.LengthField(
                        help_text="Full circumference, in inches",
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="full bust/chest",
                    ),
                ),
                (
                    "upper_torso_circ",
                    customfit.fields.LengthField(
                        blank=True,
                        help_text="Full circumference, in inches",
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="upper torso circumference",
                    ),
                ),
                (
                    "wrist_circ",
                    customfit.fields.LengthField(
                        help_text="Full circumference, in inches",
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="wrist circumference",
                    ),
                ),
                (
                    "forearm_circ",
                    customfit.fields.LengthField(
                        blank=True,
                        help_text="Full circumference, in inches",
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="forearm circumference",
                    ),
                ),
                (
                    "bicep_circ",
                    customfit.fields.LengthField(
                        help_text="Full circumference, in inches",
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="bicep circumference",
                    ),
                ),
                (
                    "elbow_circ",
                    customfit.fields.LengthField(
                        blank=True,
                        help_text="Full circumference, in inches",
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="elbow circumference",
                    ),
                ),
                (
                    "armpit_to_short_sleeve",
                    customfit.fields.LengthField(
                        blank=True,
                        help_text="Distance, in inches, from armhole shaping down to the bottom of a short sleeve",
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="short sleeve to armhole",
                    ),
                ),
                (
                    "armpit_to_elbow_sleeve",
                    customfit.fields.LengthField(
                        blank=True,
                        help_text="Distance, in inches, from the armhole shaping down to the bottom of an elbow sleeve",
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="elbow sleeve to armhole",
                    ),
                ),
                (
                    "armpit_to_three_quarter_sleeve",
                    customfit.fields.LengthField(
                        blank=True,
                        help_text="Distance, in inches, from armhole shaping down to the bottom of a three-quarter sleeve",
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="3/4 sleeve to armhole",
                    ),
                ),
                (
                    "armpit_to_full_sleeve",
                    customfit.fields.LengthField(
                        help_text="Distance, in inches, from armhole shaping down to the bottom of a full sleeve",
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="long sleeve length (from armhole to cuff)",
                    ),
                ),
                (
                    "inter_nipple_distance",
                    customfit.fields.LengthField(
                        blank=True,
                        help_text="In inches",
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="inter-nipple distance",
                    ),
                ),
                (
                    "armpit_to_waist",
                    customfit.fields.LengthField(
                        blank=True,
                        help_text="Length (in inches), from armhole-shaping to waist",
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="waist (up) to armhole shaping",
                    ),
                ),
                (
                    "armhole_depth",
                    customfit.fields.PositiveLengthField(
                        help_text="In inches, from shoulder going straight down to armhole height",
                        validators=[customfit.fields.LowerLimitValidator(0)],
                        verbose_name="armhole depth",
                    ),
                ),
                (
                    "armpit_to_high_hip",
                    customfit.fields.LengthField(
                        blank=True,
                        help_text="Length (in inches) from armhole-shaping to high-hip",
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="short sweater length from armhole to hem",
                    ),
                ),
                (
                    "high_hip_circ",
                    customfit.fields.PositiveLengthField(
                        blank=True,
                        help_text="Circumference (in inches) around body at high-hip",
                        null=True,
                        validators=[customfit.fields.LowerLimitValidator(0)],
                        verbose_name="body circumference at short sweater hem",
                    ),
                ),
                (
                    "armpit_to_med_hip",
                    customfit.fields.LengthField(
                        help_text="Length (in inches) from armhole-shaping to medium-hip",
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="average sweater length from armhole to hem",
                    ),
                ),
                (
                    "med_hip_circ",
                    customfit.fields.PositiveLengthField(
                        help_text="Circumference (in inches) around body at medium-hip",
                        validators=[customfit.fields.LowerLimitValidator(0)],
                        verbose_name="body circumference at average sweater hem",
                    ),
                ),
                (
                    "armpit_to_low_hip",
                    customfit.fields.LengthField(
                        blank=True,
                        help_text="Length (in inches) from armhole-shaping to low-hip",
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="long sweater length from armhole to hem",
                    ),
                ),
                (
                    "low_hip_circ",
                    customfit.fields.PositiveLengthField(
                        blank=True,
                        help_text="Circumference (in inches) around body at low-hip",
                        null=True,
                        validators=[customfit.fields.LowerLimitValidator(0)],
                        verbose_name="body circumference at long sweater hem",
                    ),
                ),
                (
                    "armpit_to_tunic",
                    customfit.fields.LengthField(
                        blank=True,
                        help_text="Length (in inches) from armhole-shaping to tunic-length",
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="tunic sweater length from armhole to hem",
                    ),
                ),
                (
                    "tunic_circ",
                    customfit.fields.PositiveLengthField(
                        blank=True,
                        help_text="Circumference (in inches) around body at tunic-hem height",
                        null=True,
                        validators=[customfit.fields.LowerLimitValidator(0)],
                        verbose_name="body circumference at tunic sweater hem",
                    ),
                ),
                (
                    "cross_chest_distance",
                    customfit.fields.PositiveLengthField(
                        blank=True,
                        help_text='Optional. (If left blank, subsequent models will compute "             "a default value where needed.',
                        null=True,
                        validators=[customfit.fields.LowerLimitValidator(0)],
                        verbose_name="cross-chest distance",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("creation_date", models.DateTimeField(auto_now_add=True)),
                ("notes", models.TextField(blank=True)),
                ("archived", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name_plural": "bodies",
                "ordering": ["creation_date"],
            },
        ),
        migrations.CreateModel(
            name="Grade",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "waist_circ",
                    customfit.fields.LengthField(
                        help_text="Full circumference, in inches",
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="waist circumference",
                    ),
                ),
                (
                    "bust_circ",
                    customfit.fields.LengthField(
                        help_text="Full circumference, in inches",
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="full bust/chest",
                    ),
                ),
                (
                    "upper_torso_circ",
                    customfit.fields.LengthField(
                        blank=True,
                        help_text="Full circumference, in inches",
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="upper torso circumference",
                    ),
                ),
                (
                    "wrist_circ",
                    customfit.fields.LengthField(
                        help_text="Full circumference, in inches",
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="wrist circumference",
                    ),
                ),
                (
                    "forearm_circ",
                    customfit.fields.LengthField(
                        blank=True,
                        help_text="Full circumference, in inches",
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="forearm circumference",
                    ),
                ),
                (
                    "bicep_circ",
                    customfit.fields.LengthField(
                        help_text="Full circumference, in inches",
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="bicep circumference",
                    ),
                ),
                (
                    "elbow_circ",
                    customfit.fields.LengthField(
                        blank=True,
                        help_text="Full circumference, in inches",
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="elbow circumference",
                    ),
                ),
                (
                    "armpit_to_short_sleeve",
                    customfit.fields.LengthField(
                        blank=True,
                        help_text="Distance, in inches, from armhole shaping down to the bottom of a short sleeve",
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="short sleeve to armhole",
                    ),
                ),
                (
                    "armpit_to_elbow_sleeve",
                    customfit.fields.LengthField(
                        blank=True,
                        help_text="Distance, in inches, from the armhole shaping down to the bottom of an elbow sleeve",
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="elbow sleeve to armhole",
                    ),
                ),
                (
                    "armpit_to_three_quarter_sleeve",
                    customfit.fields.LengthField(
                        blank=True,
                        help_text="Distance, in inches, from armhole shaping down to the bottom of a three-quarter sleeve",
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="3/4 sleeve to armhole",
                    ),
                ),
                (
                    "armpit_to_full_sleeve",
                    customfit.fields.LengthField(
                        help_text="Distance, in inches, from armhole shaping down to the bottom of a full sleeve",
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="long sleeve length (from armhole to cuff)",
                    ),
                ),
                (
                    "inter_nipple_distance",
                    customfit.fields.LengthField(
                        blank=True,
                        help_text="In inches",
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="inter-nipple distance",
                    ),
                ),
                (
                    "armpit_to_waist",
                    customfit.fields.LengthField(
                        blank=True,
                        help_text="Length (in inches), from armhole-shaping to waist",
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="waist (up) to armhole shaping",
                    ),
                ),
                (
                    "armhole_depth",
                    customfit.fields.PositiveLengthField(
                        help_text="In inches, from shoulder going straight down to armhole height",
                        validators=[customfit.fields.LowerLimitValidator(0)],
                        verbose_name="armhole depth",
                    ),
                ),
                (
                    "armpit_to_high_hip",
                    customfit.fields.LengthField(
                        blank=True,
                        help_text="Length (in inches) from armhole-shaping to high-hip",
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="short sweater length from armhole to hem",
                    ),
                ),
                (
                    "high_hip_circ",
                    customfit.fields.PositiveLengthField(
                        blank=True,
                        help_text="Circumference (in inches) around body at high-hip",
                        null=True,
                        validators=[customfit.fields.LowerLimitValidator(0)],
                        verbose_name="body circumference at short sweater hem",
                    ),
                ),
                (
                    "armpit_to_med_hip",
                    customfit.fields.LengthField(
                        help_text="Length (in inches) from armhole-shaping to medium-hip",
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="average sweater length from armhole to hem",
                    ),
                ),
                (
                    "med_hip_circ",
                    customfit.fields.PositiveLengthField(
                        help_text="Circumference (in inches) around body at medium-hip",
                        validators=[customfit.fields.LowerLimitValidator(0)],
                        verbose_name="body circumference at average sweater hem",
                    ),
                ),
                (
                    "armpit_to_low_hip",
                    customfit.fields.LengthField(
                        blank=True,
                        help_text="Length (in inches) from armhole-shaping to low-hip",
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="long sweater length from armhole to hem",
                    ),
                ),
                (
                    "low_hip_circ",
                    customfit.fields.PositiveLengthField(
                        blank=True,
                        help_text="Circumference (in inches) around body at low-hip",
                        null=True,
                        validators=[customfit.fields.LowerLimitValidator(0)],
                        verbose_name="body circumference at long sweater hem",
                    ),
                ),
                (
                    "armpit_to_tunic",
                    customfit.fields.LengthField(
                        blank=True,
                        help_text="Length (in inches) from armhole-shaping to tunic-length",
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="tunic sweater length from armhole to hem",
                    ),
                ),
                (
                    "tunic_circ",
                    customfit.fields.PositiveLengthField(
                        blank=True,
                        help_text="Circumference (in inches) around body at tunic-hem height",
                        null=True,
                        validators=[customfit.fields.LowerLimitValidator(0)],
                        verbose_name="body circumference at tunic sweater hem",
                    ),
                ),
                (
                    "cross_chest_distance",
                    customfit.fields.PositiveLengthField(
                        blank=True,
                        help_text='Optional. (If left blank, subsequent models will compute "             "a default value where needed.',
                        null=True,
                        validators=[customfit.fields.LowerLimitValidator(0)],
                        verbose_name="cross-chest distance",
                    ),
                ),
            ],
            options={
                "ordering": ["bust_circ"],
            },
        ),
        migrations.CreateModel(
            name="GradeSet",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "body_type",
                    models.CharField(
                        choices=[
                            ("body_type_adult_woman", "Adult woman"),
                            ("body_type_adult_man", "Adult man"),
                            ("body_type_child", "Child"),
                            ("body_type_unstated", "I'd prefer not to say"),
                        ],
                        default="body_type_unstated",
                        max_length=25,
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("creation_date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
