# Generated by Django 5.0.6 on 2025-01-25 18:39

import customfit.uploads.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("bodies", "0001_initial"),
        ("designs", "0001_initial"),
        ("patterns", "0001_initial"),
        ("swatches", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AwesomePicture",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quote", models.TextField()),
                ("picture", models.ImageField(max_length=150, upload_to="awesome")),
                (
                    "design",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="awesome_pictures",
                        to="designs.design",
                    ),
                ),
                (
                    "pattern",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="awesome_pictures",
                        to="patterns.individualpattern",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="awesome_pictures",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BodyPicture",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "picture",
                    models.ImageField(
                        max_length=150,
                        upload_to=customfit.uploads.models.get_image_path,
                    ),
                ),
                (
                    "object",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pictures",
                        to="bodies.body",
                        verbose_name="Body",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="IndividualPatternPicture",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "picture",
                    models.ImageField(
                        max_length=150,
                        upload_to=customfit.uploads.models.get_image_path,
                    ),
                ),
                (
                    "object",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pictures",
                        to="patterns.individualpattern",
                        verbose_name="Pattern",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SwatchPicture",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "picture",
                    models.ImageField(
                        max_length=150,
                        upload_to=customfit.uploads.models.get_image_path,
                    ),
                ),
                (
                    "object",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pictures",
                        to="swatches.swatch",
                        verbose_name="Swatch",
                    ),
                ),
            ],
        ),
    ]
