# Generated by Django 5.0.6 on 2025-01-25 18:39

import customfit.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Swatch",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("creation_date", models.DateTimeField(auto_now_add=True)),
                (
                    "name",
                    models.CharField(max_length=50, verbose_name="name your gauge"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="notes on swatch")),
                ("archived", models.BooleanField(default=False)),
                (
                    "stitches_number",
                    customfit.fields.PositiveFloatField(
                        help_text="Number of stitches in swatch, along 'stitches' side of swatch",
                        validators=[customfit.fields.LowerLimitValidator(0)],
                        verbose_name="stitch gauge",
                    ),
                ),
                (
                    "stitches_length",
                    customfit.fields.PositiveLengthField(
                        help_text="Precise length of the 'stitches' side of your swatch, in inches",
                        validators=[customfit.fields.LowerLimitValidator(0)],
                    ),
                ),
                (
                    "rows_length",
                    customfit.fields.PositiveLengthField(
                        help_text="Precise length of the 'rows' side of swatch, in inches",
                        validators=[customfit.fields.LowerLimitValidator(0)],
                        verbose_name="row gauge",
                    ),
                ),
                (
                    "rows_number",
                    customfit.fields.PositiveFloatField(
                        help_text="Number of rows in swatch, along 'rows' side of swatch",
                        validators=[customfit.fields.LowerLimitValidator(0)],
                    ),
                ),
                (
                    "use_repeats",
                    models.BooleanField(
                        default=False,
                        help_text="If true, swatch was made using repeats",
                    ),
                ),
                (
                    "stitches_per_repeat",
                    customfit.fields.StrictPositiveSmallIntegerField(
                        blank=True,
                        help_text="Number of stitches in a single repeat",
                        null=True,
                        validators=[customfit.fields.LowerLimitValidator(0)],
                    ),
                ),
                (
                    "additional_stitches",
                    customfit.fields.NonNegSmallIntegerField(
                        blank=True,
                        help_text="Number of stitches in addition to the repeated stitches (both before and after, combined)",
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("yarn_name", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "yarn_maker",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="yarn company",
                    ),
                ),
                (
                    "length_per_hank",
                    customfit.fields.LongLengthField(
                        blank=True,
                        help_text="How much yarn (in yards) in a hank?",
                        null=True,
                        validators=[customfit.fields.LowerLimitValidator(0)],
                        verbose_name="length per skein",
                    ),
                ),
                (
                    "weight_per_hank",
                    customfit.fields.GramsField(
                        blank=True,
                        help_text="How much does a hank weigh (in grams)?",
                        null=True,
                        validators=[customfit.fields.LowerLimitValidator(0)],
                        verbose_name="weight per skein",
                    ),
                ),
                (
                    "full_swatch_height",
                    customfit.fields.PositiveLengthField(
                        blank=True,
                        help_text="How long (in inches) is the full swatch along the row edge?",
                        null=True,
                        validators=[customfit.fields.LowerLimitValidator(0)],
                        verbose_name="full height of swatch",
                    ),
                ),
                (
                    "full_swatch_width",
                    customfit.fields.PositiveLengthField(
                        blank=True,
                        help_text="How long (in inches) is the full swatch along the stitch edge?",
                        null=True,
                        validators=[customfit.fields.LowerLimitValidator(0)],
                        verbose_name="full width of swatch",
                    ),
                ),
                (
                    "full_swatch_weight",
                    customfit.fields.GramsField(
                        blank=True,
                        help_text="How much does the full swatch weigh, in grams?",
                        null=True,
                        validators=[customfit.fields.LowerLimitValidator(0)],
                        verbose_name="weight of swatch (in grams)",
                    ),
                ),
                (
                    "needle_size",
                    models.CharField(
                        blank=True,
                        help_text="This will be treated as text, so please describe your needles however it makes sense to you.",
                        max_length=100,
                        null=True,
                        verbose_name="needle info",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "swatches",
                "ordering": ["creation_date"],
            },
        ),
    ]
