# Generated by Django 5.0.6 on 2025-01-25 18:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("swatches", "0001_initial"),
        ("uploads", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="swatch",
            name="featured_pic",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="uploads.swatchpicture",
            ),
        ),
        migrations.AddField(
            model_name="swatch",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="swatches",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
